version: "3"
services:

  php:
    build: ./docker-configs/php
    volumes:
      - ./src:/var/www/html
      - $HOME/xbxbwiki-docker/conf:/var/www/html/conf
      - $HOME/xbxbwiki-docker/data:/var/www/html/data

  caddy:
    image: abiosoft/caddy:php
    volumes:
      - ./docker-configs/caddy/Caddyfile_dev:/etc/Caddyfile
      - ./docker-configs/caddy/dokuwiki_php.conf:/etc/dokuwiki_php.conf
      - $HOME/xbxbwiki-docker/certs:/etc/caddycerts
      - ./src:/var/www/html
      - $HOME/xbxbwiki-docker/conf:/var/www/html/conf
      - $HOME/xbxbwiki-docker/data:/var/www/html/data
    environment:
      CADDYPATH: /etc/caddycerts

  proxy:
    image: nginx:latest
    volumes:
      - ./docker-configs/nginx:/etc/nginx
    ports:
      - "80:80"
