version: "3"
services:
  php:
    build: ./docker-configs/php
    volumes:
      - ./src:/var/www/html
      - $HOME/xbxbwiki-docker/conf:/var/www/html/conf
      - $HOME/xbxbwiki-docker/data:/var/www/html/data
  caddy:
    build:
      context: ./docker-configs/caddy
      dockerfile: Dockerfile
      args:
        address: "0.0.0.0:80"
    volumes:
      - $HOME/xbxbwiki-docker/certs:/etc/caddycerts
      - ./src:/srv
      - $HOME/xbxbwiki-docker/conf:/srv/conf
      - $HOME/xbxbwiki-docker/data:/srv/data
    environment:
      CADDYPATH: /etc/caddycerts
  proxy:
    image: nginx:latest
    volumes:
      - ./docker-configs/nginx:/etc/nginx
    ports:
      - "80:80"
