version: "3"
services:
  xbxbwiki:
    image: php:7.0-apache
    volumes:
      - ./src:/var/www/html
      - $HOME/xbxbwiki-docker/conf:/var/www/html/conf
      - $HOME/xbxbwiki-docker/data:/var/www/html/data
    restart: always

  proxy:
    image: nginx:latest
    volumes:
      - ./docker-configs/nginx:/etc/nginx
    restart: always
    ports:
      - "80:80"
