version: "3"
services:
  caddy:
    image: abiosoft/caddy:php
    volumes:
      - ./docker-configs/caddy/Caddyfile:/etc/Caddyfile
      - /etc/caddycerts:/etc/caddycerts
      - /var/www/html/xb2wiki:/srv
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      CADDYPATH: /etc/caddycerts
  php:
    image: php:7.0-fpm-alpine
    volumes:
      - ./docker-configs/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker-configs/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - /var/www/html/xb2wiki:/var/www/html
    restart: always
