version: "3"
services:
  php:
    build: ./docker-configs/php
    volumes:
      - ./src:/var/www/html
      - /xb2wiki/conf:/var/www/html/conf
      - /xb2wiki/data:/var/www/html/data
  caddy:
    build:
      context: ./docker-configs/caddy
      dockerfile: Dockerfile
      args:
        address: "http://xenoblade2.cn:80"
    volumes:
      - /etc/caddycerts:/etc/caddycerts
      - ./src:/srv
      - /xb2wiki/conf:/srv/conf
      - /xb2wiki/data:/srv/data
    environment:
      CADDYPATH: /etc/caddycerts
    ports:
      - 80:80
      - 443:443
